public class Constants {
    public static final String BEARER_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiNWQ4MDFmNGMxOWI0NGExMmEwMjNiZjJhIiwidXNlcm5hbWUiOiJOZXcgTmFtZSJ9LCJpYXQiOjE1NzA3MjQ4MjAsImV4cCI6MTU3MDgxMTIyMH0.9giDKIel9P_iwKtu9pwCGFk_U6KQ0IdHb7Snjet1rnY";
}
